### ISSUE TITLE
Another eroor

### ISSUE THREAD

**Issue by Swift12gaming** [IkeVoodoo/LSSMP#104]
Cannot load plugins/Lifesteal-Smp-Plugin/config.yml
org.bukkit.configuration.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:java.util.UUID
 in 'string', line 19, column 43:
     ... 8e-10f5-3e13-97a5-04aca8d19163: !!java.util.UUID 'c845e55e-ac7d- ... 
                                         ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:158) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:134) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.java.JavaPlugin.saveConfig(JavaPlugin.java:171) ~[patched_1.17.1.jar:git-Purpur-1415]
        at me.ikevoodoo.lifestealsmpplugin.LifestealSmpPlugin.onEnable(LifestealSmpPlugin.java:62) ~[lifesteal-smp-plugin-1.6.4.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1415]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: could not determine a constructor for the tag tag:yaml.org,2002:java.util.UUID
 in 'string', line 19, column 43:
     ... 8e-10f5-3e13-97a5-04aca8d19163: !!java.util.UUID 'c845e55e-ac7d- ... 
                                         ^

        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:574) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:174) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:158) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.17.1.jar:git-Purpur-1415]
        ... 17 more

**Comment by Swift12gaming** [comment]
> try using a different version suited for your server min 1.17.1

> try using a different version suited for your server version

my server is in 1.17.1 and im on the latest version of livesteal plugin

**Comment by Swift12gaming** [comment]
> Your config is broken, delete it and restart the server

it's the default config

**Comment by IkeVoodoo** [comment]
delete the config, and restart it, something broke while saving
