### ISSUE TITLE
Not starting on spigot 1.17.1

### ISSUE THREAD

**Issue by zacharyqueralt** [IkeVoodoo/LSSMP#4]
I just downloaded the latest plugin jar and it is saying is it up to date, is this because I'm using spigot and not paper, if it is would I just be able to force start the plugin by changing the code that checks the server version. or will I have to resort to using paper.

[23:15:21] [Server thread/INFO]: [Lifesteal-Smp-Plugin] Enabling Lifesteal-Smp-Plugin v1.5.1.2
[23:15:21] [Server thread/ERROR]: Error occurred while enabling Lifesteal-Smp-Plugin v1.5.1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
	at me.ikevoodoo.lifestealsmpplugin.LifestealSmpPlugin.onEnable(LifestealSmpPlugin.java:34) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 11 more
[23:15:21] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:15:21] [Server thread/INFO]: Done (34.520s)! For help, type "help"

**Comment by IkeVoodoo** [comment]
Hello, yes you indeed have to use paper, however I am working on bringing the plugin to more servers and more versions
