### ISSUE TITLE
I tried to change the should ban to true but it doesn't work

### ISSUE THREAD

**Issue by Xenxen318** [IkeVoodoo/LSSMP#69]
elimination:
  spectate:
    killerDisconnected: '&cYour killer has disconnected!'
    shouldSpectate: true
    killerNotOnline: '&cYour killer is not online so you are not allowed to spectate!'
  bans:
    broadcastBan: false
    broadcastMessage: '&c%player% has lost all of it''s hearts and has been banned.'
    banMessage: '&cYou been banned due to loosing all of your hearts, your last killer
      was &4%player%'
    shouldBan: false
  shouldEliminate: true
  scaleHealth: true
  healthScale: 1.0
  environmentStealsHearts: false
eliminated:
  killers:

I changed shouldban to true. After awhile it change back to false

How to fix it.

**Comment by IkeVoodoo** [comment]
try doing /lsreload after saving the config

**Comment by ZyroCube** [comment]
I am having the same thing

**Comment by IkeVoodoo** [comment]
I don't know the problem here, I am gonna update the plugin soon hope I fixed it

**Comment by Xenxen318** [comment]
> try doing /lsreload after saving the config
I tried like 10x time. It doesn't work out or it ban ppl for no reason?

**Comment by IkeVoodoo** [comment]
weird, send me logs

**Comment by Xenxen318** [comment]
[01:45:10] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[01:45:10] [main/INFO]: Reloading ResourceManager: Default, bukkit
[01:45:12] [Worker-Main-1/INFO]: Loaded 7 recipes
[01:45:14] [Server thread/INFO]: Starting minecraft server version 1.17.1
[01:45:14] [Server thread/INFO]: Loading properties
[01:45:14] [Server thread/INFO]: This server is running Paper version git-Paper-263 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3069eae)
[01:45:14] [Server thread/INFO]: Server Ping Player Sample Count: 12
[01:45:14] [Server thread/INFO]: Using 4 threads for Netty based IO
[01:45:14] [Server thread/INFO]: Default game type: SURVIVAL
[01:45:14] [Server thread/INFO]: Generating keypair
[01:45:14] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:28145
[01:45:14] [Server thread/INFO]: Using epoll channel type
[01:45:14] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[01:45:14] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[01:45:15] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[01:45:21] [Server thread/WARN]: Legacy plugin SimpleTpa v5.5 does not specify an api-version.
[01:45:21] [Server thread/WARN]: Legacy plugin SetHome v5.1.2 does not specify an api-version.
[01:45:22] [Server thread/WARN]: Legacy plugin EpicGuard v5.3.0 does not specify an api-version.
[01:45:23] [Server thread/INFO]: [SimpleTpa] Loading SimpleTpa v5.5
[01:45:23] [Server thread/INFO]: [LagAssist] Loading LagAssist v2.24.1
[01:45:23] [Server thread/INFO]: [SetHome] Loading SetHome v5.1.2
[01:45:23] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.47
[01:45:23] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.6+4b2d1e7
[01:45:24] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@2abf767c]
[01:45:24] [Server thread/INFO]: [NoPlugins] Loading NoPlugins v7.3.3
[01:45:24] [Server thread/INFO]: [SkinsRestorer] Loading SkinsRestorer v14.1.3
[01:45:24] [Server thread/INFO]: [Essentials] Loading Essentials v2.19.0
[01:45:24] [Server thread/INFO]: [Lifesteal-Smp-Plugin] Loading Lifesteal-Smp-Plugin v1.6.4.0
[01:45:24] [Server thread/INFO]: [ClearLag] Loading ClearLag v3.2.2
[01:45:24] [Server thread/INFO]: [EpicGuard] Loading EpicGuard v5.3.0
[01:45:24] [Server thread/INFO]: [RandomSpawnPlus] Loading RandomSpawnPlus v3.4.4
[01:45:24] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.5+3827266
[01:45:24] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.7.1-SNAPSHOT-b531
[01:45:26] [Server thread/INFO]: [CoreProtect] Loading CoreProtect v20.1
[01:45:26] [Server thread/INFO]: [Spartan] Loading Spartan vBuild 423.1
[01:45:26] [Server thread/INFO]: [nLogin] Loading nLogin v9.3.3
[01:45:26] [Server thread/INFO]: [nCore] [nLogin] Connecting to the remote server api.nickuc.com...
[01:45:26] [Server thread/INFO]: [antiRedstoneClock] Loading antiRedstoneClock v1.4.1
[01:45:26] [Server thread/INFO]: [antiRedstoneClock] WorldGuard 7 found
[01:45:26] [Server thread/INFO]: [antiRedstoneClock] Flag antiredstoneclock registered
[01:45:26] [Server thread/INFO]: [Themis] Loading Themis v0.10.1
[01:45:26] [Server thread/INFO]: [IllegalStack] Loading IllegalStack v2.3
[01:45:26] [Server thread/INFO]: [PvPManager] Loading PvPManager v3.8.4
[01:45:26] [Server thread/INFO]: [SilkSpawners] Loading SilkSpawners v7.1.0
[01:45:26] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[01:45:26] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.3.47
[01:45:27] [Server thread/INFO]:         __    
[01:45:27] [Server thread/INFO]:   |    |__)   LuckPerms v5.3.47
[01:45:27] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[01:45:27] [Server thread/INFO]: 
[01:45:27] [Server thread/INFO]: [LuckPerms] Loading configuration...
[01:45:28] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[01:45:28] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[01:45:29] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[01:45:29] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 2602ms)
[01:45:29] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.6+4b2d1e7
[01:45:29] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[01:45:29] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[01:45:29] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2 as the Bukkit adapter
[01:45:31] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.7.1-SNAPSHOT-b531
[01:45:31] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[01:45:31] [Server thread/INFO]: [nLogin] Enabling nLogin v9.3.3
[01:45:32] [Server thread/INFO]: [nCore] [nLogin] Successful plugin core start. Took 916ms
[01:45:32] [Server thread/INFO]: [nLogin]          __             _       
[01:45:32] [Server thread/INFO]: [nLogin]  _ __   / /  ___   __ _(_)_ __  
[01:45:32] [Server thread/INFO]: [nLogin] | '_ \ / /  / _ \ / _` | | '_ \ 
[01:45:32] [Server thread/INFO]: [nLogin] | | | / /__| (_) | (_| | | | | |
[01:45:32] [Server thread/INFO]: [nLogin] |_| |_\____/\___/ \__, |_|_| |_|
[01:45:32] [Server thread/INFO]: [nLogin]                   |___/            
[01:45:32] [Server thread/INFO]: [nLogin]  By: www.nickuc.com - V 9.3.3
[01:45:32] [Server thread/INFO]: [nLogin] 
[01:45:33] [Server thread/INFO]: [nLogin] Performing inicialization tasks...
[01:45:33] [Server thread/WARN]: [nLogin] Loaded class io.papermc.lib.PaperLib from RandomSpawnPlus v3.4.4 which is not a depend, softdepend or loadbefore of this plugin.
[01:45:33] [Server thread/INFO]: [nLogin] nLogin was loaded in 1301ms.
[01:45:33] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[01:45:33] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[01:45:33] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[01:45:33] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[01:45:33] [Server thread/INFO]: Preparing level "world"
[01:45:35] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[01:45:35] [Server thread/INFO]: Time elapsed: 187 ms
[01:45:35] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[01:45:35] [Server thread/INFO]: Time elapsed: 16 ms
[01:45:35] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[01:45:35] [Server thread/INFO]: Time elapsed: 95 ms
[01:45:35] [Server thread/INFO]: [SimpleTpa] Enabling SimpleTpa v5.5*
[01:45:35] [Server thread/INFO]: [SimpleTpa] If you need support contact me at https://discord.gg/SZUkza9
[01:45:35] [Server thread/INFO]: [SimpleTpa] Simple Tpa has been enabled on version 5.5
[01:45:35] [Server thread/INFO]: Enabled metrics. You may opt-out by changing plugins/bStats/config.yml
[01:45:35] [Server thread/INFO]: [LagAssist] Enabling LagAssist v2.24.1
[01:45:35] [Server thread/INFO]: LagAssist » Enabling Systems:
[01:45:35] [Server thread/INFO]:     [✔] Economy manager
[01:45:35] [Server thread/INFO]:     [✔] Smart Mob Tools.
[01:45:35] [Server thread/INFO]:     [✔] MicroFeatures.
[01:45:35] [Server thread/INFO]:     [✔] Hopper Manager.
[01:45:35] [Server thread/INFO]:     [✔] Redstone Culler.
[01:45:35] [Server thread/INFO]:     [✔] Physics-Tweaker.
[01:45:35] [Server thread/INFO]:     [✔] Lag Monitor.
[01:45:35] [Server thread/INFO]:     [✔] MapVisualizer.
[01:45:35] [Server thread/INFO]:     [✔] Chunk Analyser.
[01:45:35] [Server thread/INFO]:     [✔] Chunk Limiter.
[01:45:35] [Server thread/INFO]:     [✔] StatsAnalyse.
[01:45:35] [Server thread/INFO]:     [✔] LogCleaner System.
[01:45:35] [Server thread/INFO]:     [✔] Spawner Manager.
[01:45:36] [Server thread/INFO]:     [✔] GUI.
[01:45:36] [Server thread/INFO]:     [✔] Injecting PacketListener.
[01:45:36] [Server thread/INFO]:     [✔] API Tools.
[01:45:36] [Server thread/INFO]: [SetHome] Enabling SetHome v5.1.2*
[01:45:36] [Server thread/INFO]: [NoPlugins] Enabling NoPlugins v7.3.3
[01:45:36] [Server thread/INFO]: [NoPlugins] Minecraft version: v1_17_R1
[01:45:36] [Server thread/INFO]: [NoPlugins] Successfully loaded.
[01:45:36] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.1.3
[01:45:36] [Server thread/INFO]: [SkinsRestorer] Using PaperSkinRefresher
[01:45:36] [Server thread/INFO]: [SkinsRestorer] Detected Minecraft v1_17_R1, using PaperSkinRefresher.
[01:45:36] [Server thread/INFO]: [SkinsRestorer] [ACF] Enabled Asynchronous Tab Completion Support!
[01:45:37] [Server thread/INFO]: [Essentials] Enabling Essentials v2.19.0
[01:45:37] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[01:45:37] [Server thread/INFO]: [Essentials] No kits found to migrate.
[01:45:38] [Server thread/INFO]: [Essentials] Loaded 36837 items from items.json.
[01:45:38] [Server thread/INFO]: [Essentials] Using locale en
[01:45:38] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[01:45:38] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[01:45:38] [Server thread/WARN]: [Essentials] Detected supported permissions plugin LuckPerms without Vault installed.
[01:45:38] [Server thread/WARN]: [Essentials] Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.
[01:45:38] [Server thread/INFO]: [Essentials] Using superperms-based permissions.
[01:45:38] [Server thread/INFO]: [Lifesteal-Smp-Plugin] Enabling Lifesteal-Smp-Plugin v1.6.4.0
[01:45:38] [Server thread/ERROR]: Cannot load plugins/Lifesteal-Smp-Plugin/config.yml
org.bukkit.configuration.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:java.util.UUID
 in 'string', line 19, column 43:
     ... 5f-fa96-3c89-afec-186935d1fc2c: !!java.util.UUID '68a9a7ce-d175- ... 
                                         ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:158) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:134) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.plugin.java.JavaPlugin.saveConfig(JavaPlugin.java:171) ~[patched_1.17.1.jar:git-Paper-263]
	at me.ikevoodoo.lifestealsmpplugin.LifestealSmpPlugin.onEnable(LifestealSmpPlugin.java:62) ~[lifesteal-smp-plugin-1.6.4.0 (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-263]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-263]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-263]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-263]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-263]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: could not determine a constructor for the tag tag:yaml.org,2002:java.util.UUID
 in 'string', line 19, column 43:
     ... 5f-fa96-3c89-afec-186935d1fc2c: !!java.util.UUID '68a9a7ce-d175- ... 
                                         ^

	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:574) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:174) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:158) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.17.1.jar:git-Paper-263]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.17.1.jar:git-Paper-263]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.17.1.jar:git-Paper-263]
	... 17 more


Here's what I see after reload and restart

this is when i done config and do lsreload
[02:15:18 WARN]: org.bukkit.configuration.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:java.util.UUID
[02:15:18 WARN]:  in 'string', line 19, column 43:
[02:15:18 WARN]:      ... 39-4b4d-3c75-bc8a-ae7ad6388778: !!java.util.UUID '1c3205ca-e7b2- ... 
[02:15:18 WARN]:                                          ^
[02:15:18 WARN]: 
[02:15:18 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[02:15:18 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[02:15:18 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[02:15:18 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184)
[02:15:18 WARN]:        at lifesteal-smp-plugin-1.6.4.0 (1).jar//me.ikevoodoo.lifestealsmpplugin.Configuration.reload(Configuration.java:58)
[02:15:18 WARN]:        at lifesteal-smp-plugin-1.6.4.0 (1).jar//me.ikevoodoo.lifestealsmpplugin.commands.ReloadCommand.onCommand(ReloadCommand.java:17)
[02:15:18 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:15:18 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[02:15:18 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838)
[02:15:18 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:801)
[02:15:18 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:518)
[02:15:18 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[02:15:18 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[02:15:18 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[02:15:18 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[02:15:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[02:15:18 WARN]: Caused by: could not determine a constructor for the tag tag:yaml.org,2002:java.util.UUID
[02:15:18 WARN]:  in 'string', line 19, column 43:
[02:15:18 WARN]:      ... 39-4b4d-3c75-bc8a-ae7ad6388778: !!java.util.UUID '1c3205ca-e7b2- ... 
[02:15:18 WARN]:                                          ^
[02:15:18 WARN]: 
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:574)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[02:15:18 WARN]:        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[02:15:18 WARN]:        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[02:15:18 WARN]:        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:174)
[02:15:18 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:158)
[02:15:18 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[02:15:18 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[02:15:18 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[02:15:18 WARN]:        ... 15 more

**Comment by IkeVoodoo** [comment]
Send me your config

**Comment by Xenxen318** [comment]
> Send me your config

elimination:
  spectate:
    killerDisconnected: '&cYour killer has disconnected!'
    shouldSpectate: true
    killerNotOnline: '&cYour killer is not online so you are not allowed to spectate!'
  bans:
    broadcastBan: false
    broadcastMessage: '&c%player% has lost all of it''s hearts and has been banned.'
    banMessage: '&cYou been banned due to loosing all of your hearts, your last killer
      was &4%player%'
    shouldBan: false
  shouldEliminate: true
  scaleHealth: true
  healthScale: 1.0
  environmentStealsHearts: false
eliminated:

I tried to change it into shouldban : true
shouldspectate : false
But it change in a few mins back to the default

**Comment by IkeVoodoo** [comment]
> > Send me your config
> 
> elimination: spectate: killerDisconnected: '&cYour killer has disconnected!' shouldSpectate: true killerNotOnline: '&cYour killer is not online so you are not allowed to spectate!' bans: broadcastBan: false broadcastMessage: '&c%player% has lost all of it''s hearts and has been banned.' banMessage: '&cYou been banned due to loosing all of your hearts, your last killer was &4%player%' shouldBan: false shouldEliminate: true scaleHealth: true healthScale: 1.0 environmentStealsHearts: false eliminated:
> 
> I tried to change it into shouldban : true shouldspectate : false But it change in a few mins back to the default

Should spectate is on, should ban is off, also no need to change shouldSpectate since shouldEliminate has priority
